"use client";
import { useEffect, useState } from "react";
import { request, type Politician } from "../lib/api";
import Portrait from "./Portrait";

type Asset = { kind: string; description: string; value: string; company_url?: string | null };
type Data = { available: boolean; election_year?: number | null; total: string; assets: Asset[]; history: { year: number; total: string }[]; growth_percentage?: string | null; source_url: string; notice: string };
const brl = (value: string) => Number(value).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });

export default function Assets({ person }: { person: Politician }) {
  const [data, setData] = useState<Data | null>(null); const [error, setError] = useState("");
  useEffect(() => { const controller = new AbortController(); request<Data>(`/politicians/${person.provider}/${person.id}/assets`, controller.signal).then(setData).catch(value => { if (value?.name !== "AbortError") setError("Os bens declarados estão indisponíveis nesta consulta."); }); return () => controller.abort(); }, [person.id, person.provider]);
  return <section className="mb-10 rounded-2xl border bg-white p-6" aria-label="Bens declarados">
    <div className="flex items-center gap-4"><Portrait person={person} /><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-800">Declaração eleitoral</p><h3 className="text-2xl font-bold">Bens declarados por {person.name}</h3></div></div>
    {!data && !error && <p role="status" className="mt-4 text-sm text-slate-500">Consultando fontes públicas de patrimônio…</p>}
    {error && <p role="alert" className="mt-4 text-sm text-slate-500">{error}</p>}
    {data && <><p className="mt-5 text-sm leading-relaxed text-slate-600">{data.notice}</p>{data.available ? <><p className="mt-5 text-lg font-bold">Total publicado para {data.election_year}: {brl(data.total)}</p>{data.history?.length > 1 && <section className="mt-5 rounded-xl border bg-slate-50 p-5" aria-label="Evolução do patrimônio publicado"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-800">Evolução patrimonial publicada</p><h4 className="mt-1 text-xl font-bold">{Number(data.growth_percentage).toLocaleString("pt-BR", { maximumFractionDigits: 1 })}% desde {data.history[0].year}</h4></div><p className="text-xs text-slate-500">Comparação nominal, sem correção pela inflação</p></div><div className="mt-5 flex h-44 items-end gap-3 border-b border-slate-300">{data.history.map(item => { const maximum = Math.max(...data.history.map(point => Number(point.total)), 1); return <div className="flex h-full flex-1 flex-col justify-end text-center" key={item.year}><span className="mb-2 text-xs font-semibold">{brl(item.total)}</span><div className="mx-auto w-full max-w-20 rounded-t bg-emerald-700" style={{ height: `${Math.max(5, Number(item.total) / maximum * 100)}%` }} /><span className="mt-2 text-xs font-bold">{item.year}</span></div>; })}</div><p className="mt-5 text-xs leading-relaxed text-slate-500">O percentual compara apenas as publicações encontradas. Crescimento patrimonial, isoladamente, não indica irregularidade.</p></section>}{data.assets.length ? <div className="mt-4 grid gap-3 md:grid-cols-2">{data.assets.map((item, index) => <article className="rounded-xl bg-slate-50 p-4" key={`${item.kind}-${index}`}><p className="text-xs font-bold uppercase tracking-wide text-emerald-800">{item.kind}</p><p className="mt-2 text-sm leading-relaxed">{item.description}</p><p className="mt-3 font-bold">{brl(item.value)}</p>{item.company_url && <a href={item.company_url} target="_blank" rel="noreferrer" className="mt-2 inline-block text-sm font-bold text-emerald-800 underline">Site oficial da empresa</a>}</article>)}</div> : <p className="mt-4 text-sm">O perfil foi encontrado, mas a fonte consultada não publicou itens de patrimônio.</p>}</> : <div className="mt-4 rounded-xl bg-amber-50 p-4 text-sm leading-relaxed text-amber-950"><strong>Por que pode não aparecer?</strong> A fonte alternativa pode não ter uma página para esta pessoa, para este ano ou para o nome usado no perfil. Quando não há correspondência segura, nenhum valor é exibido.</div>}<a className="mt-5 inline-block text-sm font-bold text-emerald-800 underline" href={data.source_url} target="_blank" rel="noreferrer">Conferir a fonte consultada</a></>}
  </section>;
}
